// Generated by dev/build-journal.py from content/journal.json.
const JOURNAL_CONFIG = {
  "eyebrow": "A field journal",
  "title": "The place is the story.",
  "lead": "Notes on positioning, websites and the small decisions that help a hospitality business become easier to choose.",
  "archiveLabel": "Three notes to start",
  "archiveMeta": "Written by the people doing the work · Updated July 2026",
  "articleCtaTitle": "Have a place with a story?",
  "articleCtaLead": "If the way your property feels is stronger than the way it looks online, tell us where the gap is."
};
const JOURNAL_POSTS = [
  {
    "slug": "your-hotel-is-not-a-commodity",
    "issue": "Field note 01",
    "category": "Positioning",
    "title": "Your hotel is not a commodity. Your website is making it one.",
    "excerpt": "The quickest way to make a good property look interchangeable is to describe it with the same adjectives as everyone else.",
    "date": "July 18, 2026",
    "readTime": "6 min read",
    "accent": "terracotta"
  },
  {
    "slug": "the-story-should-survive-the-booking-page",
    "issue": "Field note 02",
    "category": "Experience",
    "title": "The story should survive the booking page.",
    "excerpt": "A story that exists only on the homepage is decoration. The useful version travels with the guest through every decision.",
    "date": "July 23, 2026",
    "readTime": "5 min read",
    "accent": "deep"
  },
  {
    "slug": "the-first-thirty-seconds-of-a-hospitality-website",
    "issue": "Field note 03",
    "category": "Websites",
    "title": "The first 30 seconds of a small hospitality website.",
    "excerpt": "A useful first screen is less about cramming in information and more about removing the three doubts that stop a guest from continuing.",
    "date": "July 29, 2026",
    "readTime": "7 min read",
    "accent": "ochre"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { JOURNAL_CONFIG, JOURNAL_POSTS };
}
